name: Check API Key and Environment Variable

on:
  push:
    branches:
      - main
      - develop

jobs:
  validate_api_key:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate API_KEY secret
      run: |
        if [ -z "${{ secrets.API_KEY }}" ]; then
          echo "API_KEY secret is not set."
          exit 1
        else
          echo "API_KEY secret is set to: ${{ secrets.API_KEY }}"
        fi
