name: Check API Key and Environment Variable

on:
  push:
    branches:
      - main

jobs:
  validate_key_and_env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate API_KEY secret
      run: |
        if [ -z "${{ secrets.API_KEY }}" ]; then
          echo "API_KEY secret is not set."
          exit 1
        else
          echo "API_KEY secret is set to: ${{ secrets.API_KEY }}"
        fi

    - name: Print APP_ENV variable
      run: |
        if [ -z "${{ env.APP_ENV }}" ]; then
          echo "APP_ENV variable is not set."
          exit 1
        else
          echo "APP_ENV is set to: ${{ env.APP_ENV }}"
        fi
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
