name: Check API Key and Environment Variable

on:
  push:
    branches:
      - main 
      - develop

jobs:
  validate_api_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate API_KEY secret
      run: |
        if [ -z "${{ secrets.API_KEY }}" ]; then
          echo "API_KEY secret, no está configurado."
          exit 1
        else
          echo "API_KEY secret está configiurado como: ${{ secrets.API_KEY }}"
        fi
